# Generated by Django 4.2.30 on 2026-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckstop',
            name='latitude',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='truckstop',
            name='longitude',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['latitude', 'longitude'], name='trip_planne_latitud_6207d7_idx'),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['retail_price'], name='trip_planne_retail__d372c6_idx'),
        ),
    ]
